### ISSUE TITLE
OutOfMemoryError when running at android platform

### ISSUE THREAD

**Issue by luchas** [naveenthontepu/PictureCompression#1]
Process: com.example.piccompress, PID: 11068
                  java.lang.OutOfMemoryError: Failed to allocate a 31961100 byte allocation
                      at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                      at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
                      at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:554)
                      at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:577)
                      at com.example.piccompress.MainActivity.uploadFile(MainActivity.java:175)
                      at com.example.piccompress.MainActivity.onActivityResult(MainActivity.java:139)
                      at android.app.Activity.dispatchActivityResult(Activity.java:6226)

locate at :
        Bitmap compressed = BitmapFactory.decodeByteArray(out.toByteArray(), 0, out.size());

**Comment by naveenthontepu** [comment]
Decoding of byte array is happening in Main Thread so use an Async task to run compression in a different thread and use BitmapFactory.Options while decoding file so that initial huge bitmap would not be stored in memory while scaling is done. 
I will update code which i have changed.
